#!/bin/sh

apt-get update -y &&
apt-get upgrade -y &&
apt-get install -y build-essential &&
apt-get install -y git wget curl nano redis-server nginx software-properties-common libnotify-bin && 

curl -sL https://deb.nodesource.com/setup_9.x | bash - &&
apt-get update &&
apt-get install -y nodejs &&

cd $HOME &&
git clone https://github.com/DialogueSolutions/etc-netstats.git &&
cd etc-netstats &&
npm install &&
npm install -g grunt-cli &&

ln -s /.etc-netstats $HOME/
